### ISSUE TITLE
Matomo 4.0

### ISSUE THREAD

**Issue by BastianBalthasarBux** [DevDavido/performance-audit-plugin#30]
Would be cool, this plugin gets compatible with Matomo 4!

**Comment by DevDavido** [comment]
Have you tried the beta releases of this plugin for Matomo 4? I just released another beta version 3 containing the latest updates. Does it work for you?

**Comment by BastianBalthasarBux** [comment]
`PerformanceAudit plugin activation failed due to the following error: Node.js dependency installation failed due to the following error: npm dependency not found.`

I tried different open_basedir settings, also the suggested ones. Not sure, what is the problem. It worked on that server before with my personal default settings.

**Comment by DevDavido** [comment]
The plugin cannot find the `npm` executable in that case. Can PHP and the user running PHP files access the npm executable?

Which version you used when you installed the plugin?

**Comment by BastianBalthasarBux** [comment]
Ok, not sure, if I already installed npm before. But I am wondering, why it worked before ... I'll have a deeper look at it and get back to you.

**Comment by almare** [comment]
Same problem here with the 2.0 version. On console I get a a longer error log. Maybe this helps.

```
Node.js dependency installation failed due to the following error: 
NPM has the following unexpected output: 
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/var/www/clients/client0/web14/web/plugins/PerformanceAudit/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/clients/client0/web14/web/plugins/PerformanceAudit/node_modules/puppeteer/lib/BrowserFetcher.js:26:20)

PerformanceAudit plugin activation failed due to the following error: 
Node.js dependency installation failed due to the following error: 
NPM has the following unexpected output: 
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/var/www/clients/client0/web14/web/plugins/PerformanceAudit/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/clients/client0/web14/web/plugins/PerformanceAudit/node_modules/puppeteer/lib/BrowserFetcher.js:26:20)



                                                                                                                                              
  [Piwik\Plugins\PerformanceAudit\Exceptions\InstallationFailedException]                                                                     
  PerformanceAudit plugin activation failed due to the following error:                                                                       
  Node.js dependency installation failed due to the following error:                                                                          
  NPM has the following unexpected output:                                                                                                    
  internal/util.js:209                                                                                                                        
      throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');                                                             
      ^                                                                                                                                       
  TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function                                                          
      at promisify (internal/util.js:209:11)                                                                                                  
      at Object.<anonymous> (/var/www/clients/client0/web14/web/plugins/PerformanceAudit/node_modules/extract-zip/index.js:11:18)             
      at Module._compile (module.js:652:30)                                                                                                   
      at Object.Module._extensions..js (module.js:663:10)                                                                                     
      at Module.load (module.js:565:32)                                                                                                       
      at tryModuleLoad (module.js:505:12)                                                                                                     
      at Function.Module._load (module.js:497:3)                                                                                              
      at Module.require (module.js:596:17)                                                                                                    
      at require (internal/module.js:11:18)                                                                                                   
      at Object.<anonymous> (/var/www/clients/client0/web14/web/plugins/PerformanceAudit/node_modules/puppeteer/lib/BrowserFetcher.js:26:20)  
```

**Comment by Grienauer** [comment]
I got also the same folder node is available…
here a screencapture to see the installation problem in progress.
https://www.loom.com/share/4acaa633eb2d4e36825d9c4e7e56839d

If I should test something, just send me what and how if that helps to debug it.
thx!

**Comment by Grienauer** [comment]
I don't think this issue should be closed, because the problem is still there :P

**Comment by jr-ewing** [comment]
I have the same problem. What should i test ? What Information do you need ?
Node.js and NPM are installed. 

ERROR_LOG:

2021/09/04 14:02:35 [error] 29464#0: *321392 FastCGI sent in stderr: "PHP message: Error in Matomo: PerformanceAudit plugin activation failed due to the following error: Node.js dependency installation failed due to the following error: npm dependency not found. Please disable PHP open_basedir or set your PHP open_basedir option to: /var/www/vhosts/tz-tools.de/:/tmp/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vhosts/tz-tools.de/httpdocs/matomo/plugins/PerformanceAudit/composer/bin:/var/www/vhosts/tz-tools.de/httpdocs/matomo/plugins/PerformanceAudit/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" while reading response header from upstream, client: 217.83.21.205, server: www.tz-tools.de, request: "GET /matomo/index.php?module=CorePluginsAdmin&action=activate&idSite=1&period=day&date=yesterday&showtitle=1&random=9228&sort=&embed=0&pluginName=PerformanceAudit&nonce=16064f1edc13ee61b2e369863f06a7d4&mode=admin&redirectTo=marketplace HTTP/2.0", upstream: "fastcgi://unix:///var/www/vhosts/system/tz-tools.de/php-fpm.sock:", host: "www.tz-tools.de", referrer: "https://www.tz-tools.de/matomo/index.php?module=Marketplace&action=installPlugin&idSite=1&period=day&date=yesterday&showtitle=1&random=9228&sort=&embed=0&pluginName=PerformanceAudit&nonce=53ef52edb5729ff9e621a76f99a9091c&mode=admin"

**Comment by Findus23** [comment]
@jr-ewing Where do you have `npm` installed on the server`? Maybe check with `which npm`. And make sure PHP is able to access this path.

**Comment by DevDavido** [comment]
@jr-ewing See @Findus23's reply
@Grienauer It seems the node binary isn't accessible. What does executing `which node` output on your server shell?

**Comment by jr-ewing** [comment]
which npm returns: 

/usr/bin/npm

My open_basedir
{WEBSPACEROOT}{/}{:}{TMP}{/}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Should i add /usr/bin/npm ? Is /usr/bin not enought?

**Comment by DevDavido** [comment]
@jr-ewing What server OS you are using? If you use e.g. Ubuntu you could run to install the required chrome dependencies:
```shell
apt-get update && apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm-dev libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget```

**Comment by jr-ewing** [comment]
As soon as you do it right, it works :-D Seems to work - thank you ;-)
